name: Dokemon Server
description: Dokemon game server for Home Assistant
version: "1.0.0"
slug: dokemon_server
arch:
  - amd64
  - armv7
  - aarch64
image: javastraat/dokemon-server:latest
ports:
  "9090/tcp": 9090
volumes:
  data: /data
  docker_sock: /var/run/docker.sock
